<x-layouts.app title="Matrículas">
    <div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <form class="flex flex-1 flex-col gap-2 sm:flex-row"><input class="field max-w-md" name="search" value="{{ request('search') }}" placeholder="Buscar aluno"><select class="field max-w-48" name="status"><option value="">Todos os status</option><option value="active" @selected(request('status') === 'active')>Ativas</option><option value="paused" @selected(request('status') === 'paused')>Pausadas</option><option value="cancelled" @selected(request('status') === 'cancelled')>Canceladas</option></select><button class="btn-secondary">Filtrar</button></form>
        <a class="btn-primary" href="{{ route('memberships.create') }}">+ Nova matrícula</a>
    </div>
    <div class="card overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Aluno</th><th class="px-6 py-4">Plano</th><th class="px-6 py-4">Início</th><th class="px-6 py-4">Valor</th><th class="px-6 py-4">Status</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($memberships as $membership)<tr><td class="px-6 py-4"><p class="font-bold text-ink-950">{{ $membership->member->name }}</p><p class="text-xs text-slate-500">Vencimento dia {{ $membership->billing_day }}</p></td><td class="px-6 py-4">{{ $membership->plan->name }}</td><td class="px-6 py-4">{{ $membership->starts_at->format('d/m/Y') }}</td><td class="px-6 py-4 font-semibold">R$ {{ number_format($membership->price, 2, ',', '.') }}</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $membership->status === 'active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ ['active' => 'Ativa', 'paused' => 'Pausada', 'cancelled' => 'Cancelada'][$membership->status] ?? $membership->status }}</span></td><td class="px-6 py-4 text-right"><a class="font-semibold text-brand-700" href="{{ route('memberships.show', $membership) }}">Detalhes →</a></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-slate-500">Nenhuma matrícula encontrada.</td></tr>@endforelse
    </tbody></table></div><div class="mt-6">{{ $memberships->links() }}</div>
</x-layouts.app>
