<x-layouts.app title="Visão geral">
    <section class="relative mb-6 overflow-hidden rounded-3xl bg-ink-950 p-6 text-white sm:p-8">
        <div class="absolute -right-12 -top-16 size-56 rounded-full border-[34px] border-brand-500/10"></div>
        <div class="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-end">
            <div><p class="text-sm text-brand-500">Olá, {{ str(auth()->user()->name)->before(' ') }}.</p><h2 class="mt-2 max-w-xl text-2xl font-black leading-tight sm:text-3xl">Sua academia, organizada e em movimento.</h2><p class="mt-2 text-sm text-slate-400">Acompanhe os números e acesse rapidamente o que precisa.</p></div>
            @can('workouts.manage')<a href="{{ route('workouts.create') }}" class="btn-primary shrink-0"><x-icon name="plus"/>Elaborar treino</a>@endcan
        </div>
    </section>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        @can('memberships.manage')<a href="{{ route('memberships.index') }}" class="card group p-5 transition hover:border-brand-100 hover:shadow-md"><div class="flex items-start justify-between"><div><p class="text-sm font-medium text-slate-500">Matrículas ativas</p><p class="mt-3 text-3xl font-black text-ink-950">{{ $membershipCount }}</p></div><span class="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><x-icon name="membership"/></span></div><p class="mt-4 flex items-center gap-1 text-xs font-bold text-brand-700">Ver matrículas <x-icon name="arrow-right" size="size-3.5"/></p></a>@endcan
        @can('billing.manage')
            <a href="{{ route('finance.index', ['status'=>'overdue']) }}" class="card group border-red-100 p-5 transition hover:shadow-md"><div class="flex items-start justify-between"><div><p class="text-sm font-medium text-red-600">Inadimplência</p><p class="mt-3 text-3xl font-black text-red-700">R$ {{ number_format($overdueAmount,2,',','.') }}</p></div><span class="grid size-10 place-items-center rounded-xl bg-red-50 text-red-600"><x-icon name="finance"/></span></div><p class="mt-4 text-xs font-bold text-red-600">Revisar pendências</p></a>
            <a href="{{ route('finance.index', ['status'=>'paid']) }}" class="card group border-emerald-100 p-5 transition hover:shadow-md"><div class="flex items-start justify-between"><div><p class="text-sm font-medium text-emerald-600">Recebido no mês</p><p class="mt-3 text-3xl font-black text-emerald-700">R$ {{ number_format($receivedThisMonth,2,',','.') }}</p></div><span class="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><x-icon name="finance"/></span></div><p class="mt-4 text-xs font-bold text-emerald-700">Ver recebimentos</p></a>
        @endcan
        @can('members.view')<div class="card p-5"><p class="text-sm font-medium text-slate-500">Alunos cadastrados</p><p class="mt-3 text-3xl font-black text-ink-950">{{ $memberCount }}</p></div>@endcan
        @can('exercises.manage')<div class="card p-5"><p class="text-sm font-medium text-slate-500">Exercícios ativos</p><p class="mt-3 text-3xl font-black text-ink-950">{{ $exerciseCount }}</p></div>@endcan
        <div class="card p-5"><p class="text-sm font-medium text-slate-500">Treinos ativos</p><p class="mt-3 text-3xl font-black text-brand-600">{{ $workoutCount }}</p></div>
    </div>

    @can('workouts.view')<div class="card mt-6 overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6"><div><h3 class="font-bold text-ink-950">Treinos recentes</h3><p class="mt-0.5 text-xs text-slate-500">Últimas fichas elaboradas</p></div><a href="{{ route('workouts.index') }}" class="text-xs font-bold text-brand-700">Ver todos</a></div><div class="divide-y divide-slate-100">@forelse($workouts as $workout)<a href="{{ route('workouts.show',$workout) }}" class="flex items-center justify-between gap-4 px-5 py-4 transition hover:bg-slate-50 sm:px-6"><div class="min-w-0"><p class="truncate font-semibold text-ink-950">{{ $workout->name }}</p><p class="truncate text-sm text-slate-500">{{ $workout->member->name }}</p></div><div class="shrink-0 text-right"><p class="text-sm font-medium">{{ $workout->starts_at->format('d/m/Y') }}</p><span class="hidden text-xs text-brand-600 sm:inline">Ver treino →</span></div></a>@empty<div class="px-6 py-12 text-center text-sm text-slate-500">Nenhum treino elaborado ainda.</div>@endforelse</div></div>@endcan
</x-layouts.app>
