<x-layouts.app title="Detalhes da matrícula">
    @php($statusLabels = ['pending' => 'Pendente', 'partial' => 'Parcial', 'paid' => 'Pago', 'overdue' => 'Vencida', 'cancelled' => 'Cancelada'])
    @php($statusClasses = ['pending' => 'bg-amber-50 text-amber-700', 'partial' => 'bg-blue-50 text-blue-700', 'paid' => 'bg-emerald-50 text-emerald-700', 'overdue' => 'bg-red-50 text-red-700', 'cancelled' => 'bg-slate-100 text-slate-500'])
    <div class="card p-6 lg:p-8"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><p class="text-sm font-bold uppercase tracking-wider text-brand-600">{{ $membership->plan->name }}</p><h2 class="mt-2 text-2xl font-black text-ink-950">{{ $membership->member->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $membership->member->email }} · vencimento dia {{ $membership->billing_day }}</p></div><div class="text-left md:text-right"><p class="text-2xl font-black text-ink-950">R$ {{ number_format($membership->price, 2, ',', '.') }}</p><p class="text-xs text-slate-400">a cada {{ $membership->plan->billing_interval_months }} mês(es)</p></div></div>
        <div class="mt-6 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-5"><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{{ $membership->status === 'active' ? 'Ativa' : ucfirst($membership->status) }}</span><span class="text-sm text-slate-500">Desde {{ $membership->starts_at->format('d/m/Y') }}</span>@if($membership->status === 'active')<form method="POST" action="{{ route('memberships.cancel', $membership) }}" class="ml-auto" onsubmit="return confirm('Cancelar esta matrícula e as cobranças futuras?')">@csrf @method('PATCH')<button class="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-red-600 transition hover:bg-red-50" title="Cancelar matrícula"><x-icon name="ban" size="size-4"/>Cancelar matrícula</button></form>@endif</div>
    </div>
    <div class="mt-8 space-y-4">
        @forelse($membership->charges as $charge)
            <article class="card overflow-hidden" x-data="{ payment: false }"><div class="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div class="min-w-52"><p class="font-bold text-ink-950">{{ $charge->description }}</p><p class="text-xs text-slate-500">Vencimento {{ $charge->due_date->format('d/m/Y') }}</p></div><div class="flex flex-1 flex-wrap items-center gap-6"><div><p class="text-xs text-slate-400">Total</p><p class="font-bold">R$ {{ number_format($charge->total, 2, ',', '.') }}</p></div><div><p class="text-xs text-slate-400">Pago</p><p class="font-bold text-emerald-700">R$ {{ number_format($charge->paid_amount, 2, ',', '.') }}</p></div><div><p class="text-xs text-slate-400">Saldo</p><p class="font-bold text-ink-950">R$ {{ number_format($charge->outstanding, 2, ',', '.') }}</p></div></div><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $statusClasses[$charge->status] ?? 'bg-slate-100' }}">{{ $statusLabels[$charge->status] ?? $charge->status }}</span>@if(!in_array($charge->status, ['paid', 'cancelled']))<button type="button" class="btn-primary" @click="payment = !payment" :aria-expanded="payment"><span x-show="!payment"><x-icon name="payment" size="size-4"/></span><span x-show="payment"><x-icon name="close" size="size-4"/></span><span x-text="payment ? 'Fechar' : 'Receber'"></span></button>@endif</div>
                <div x-show="payment" x-cloak class="border-t border-slate-100 bg-slate-50 p-5"><form method="POST" action="{{ route('payments.store', $charge) }}" class="grid gap-4 md:grid-cols-2 xl:grid-cols-5">@csrf<div><label class="label">Valor</label><input class="field" type="number" name="amount" min="0.01" max="{{ $charge->outstanding }}" step="0.01" value="{{ $charge->outstanding }}" required></div><div><label class="label">Data</label><input class="field" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></div><div><label class="label">Forma</label><select class="field" name="method"><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option><option value="bank_transfer">Transferência</option></select></div><div><label class="label">Observação</label><input class="field" name="notes"></div><div class="flex items-end"><button class="btn-primary w-full"><x-icon name="check" size="size-4"/>Confirmar pagamento</button></div></form></div>
                @if($charge->payments->isNotEmpty())<div class="border-t border-slate-100 px-5 py-3 text-xs text-slate-500">@foreach($charge->payments as $payment)<span class="mr-4">{{ $payment->paid_at->format('d/m/Y H:i') }} · R$ {{ number_format($payment->amount, 2, ',', '.') }} · {{ strtoupper($payment->method) }}</span>@endforeach</div>@endif
            </article>
        @empty<p class="py-12 text-center text-slate-500">Nenhuma cobrança gerada.</p>@endforelse
    </div>
</x-layouts.app>
