<x-layouts.app title="Alunos">
    @php
        $oldModal = old('member_modal');
        $workoutData = fn($member) => $member?->workouts->map(fn($workout) => ['id'=>$workout->id,'name'=>$workout->name,'date'=>$workout->starts_at->format('d/m/Y'),'count'=>$workout->items->count(),'open_url'=>route('workouts.show',$workout),'clone_url'=>route('workouts.create',['source_workout_id'=>$workout->id,'member_id'=>$member->id])])->values()->all() ?? [];
        $initialMember = $modalMember ? ['id' => $modalMember->id, 'name' => $modalMember->name, 'email' => $modalMember->email, 'phone' => $modalMember->phone ?? '', 'birth_date' => $modalMember->birth_date?->format('Y-m-d') ?? '', 'address' => $modalMember->address ?? '', 'active' => $modalMember->active ? '1' : '0', 'action' => route('members.update', $modalMember), 'workouts'=>$workoutData($modalMember), 'assign_url'=>route('workouts.create',['member_id'=>$modalMember->id])] : null;
        $oldMember = $oldModal ? ['id' => old('member_id'), 'name' => old('name'), 'email' => old('email'), 'phone' => old('phone', ''), 'birth_date' => old('birth_date', ''), 'address' => old('address', ''), 'active' => old('active', '1'), 'action' => old('member_action'), 'workouts'=>$workoutData($modalMember), 'assign_url'=>$modalMember?route('workouts.create',['member_id'=>$modalMember->id]):''] : null;
    @endphp
    <div x-data="memberManager({ storeUrl: @js(route('members.store')), initialMode: @js($oldModal ?: request('modal')), initialMember: @js($oldMember ?: $initialMember) })" @keydown.escape.window="close()">
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><form class="flex max-w-md flex-1 flex-col gap-2 min-[420px]:flex-row"><input class="field" name="search" value="{{ request('search') }}" placeholder="Buscar por nome ou e-mail"><button class="btn-secondary"><x-icon name="search" size="size-4" />Buscar</button></form><button type="button" class="btn-primary" @click="openCreate()"><x-icon name="plus" />Novo aluno</button></div>
        <div class="card overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Aluno</th><th class="px-6 py-4">Contato</th><th class="px-6 py-4">Status</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($members as $member)<tr><td class="px-6 py-4"><div class="flex items-center gap-3"><x-avatar :user="$member" size="sm"/><div><p class="font-semibold text-ink-950">{{ $member->name }}</p><p class="text-xs text-slate-500">{{ $member->birth_date?->format('d/m/Y') ?? 'Nascimento não informado' }}</p></div></div></td><td class="px-6 py-4"><p>{{ $member->email }}</p><p class="text-xs text-slate-500">{{ $member->phone }}</p></td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $member->active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $member->active ? 'Ativo' : 'Inativo' }}</span></td><td class="px-6 py-4 text-right"><button type="button" class="icon-btn" title="Gerenciar aluno" aria-label="Gerenciar {{ $member->name }}" @click="openEdit({{ Js::from(['id' => $member->id, 'name' => $member->name, 'email' => $member->email, 'phone' => $member->phone ?? '', 'birth_date' => $member->birth_date?->format('Y-m-d') ?? '', 'address' => $member->address ?? '', 'active' => $member->active ? '1' : '0', 'action' => route('members.update', $member), 'workouts'=>$workoutData($member), 'assign_url'=>route('workouts.create',['member_id'=>$member->id])]) }})"><x-icon name="edit" size="size-4"/></button></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-slate-500">Nenhum aluno encontrado.</td></tr>@endforelse
        </tbody></table></div><div class="mt-6">{{ $members->links() }}</div>

        <div x-show="modal" x-cloak class="fixed inset-0 z-50 overflow-y-auto" role="dialog" aria-modal="true"><div class="flex min-h-full items-end justify-center sm:items-center sm:p-6"><div class="fixed inset-0 bg-ink-950/65 backdrop-blur-sm" @click="close()"></div><form :action="form.action" method="POST" class="relative w-full rounded-t-3xl bg-white shadow-2xl sm:max-w-2xl sm:rounded-3xl">@csrf<template x-if="mode === 'edit'"><input type="hidden" name="_method" value="PUT"></template><input type="hidden" name="member_modal" :value="mode"><input type="hidden" name="member_id" :value="form.id"><input type="hidden" name="member_action" :value="form.action">
            <div class="flex items-start justify-between border-b border-slate-100 px-5 py-5 sm:px-7"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-brand-600" x-text="mode === 'edit' ? 'Atualizar cadastro' : 'Novo cadastro'"></p><h2 class="mt-1 text-xl font-black text-ink-950" x-text="mode === 'edit' ? 'Editar aluno' : 'Novo aluno'"></h2></div><button type="button" class="grid size-10 place-items-center rounded-xl text-slate-400 hover:bg-slate-100" @click="close()"><x-icon name="close" /></button></div>
            <div x-show="mode==='edit'" class="flex border-b border-slate-100 px-5 sm:px-7"><button type="button" class="border-b-2 px-3 py-3 text-sm font-bold" :class="tab==='data'?'border-brand-500 text-brand-700':'border-transparent text-slate-500'" @click="tab='data'">Dados</button><button type="button" class="border-b-2 px-3 py-3 text-sm font-bold" :class="tab==='workouts'?'border-brand-500 text-brand-700':'border-transparent text-slate-500'" @click="tab='workouts'">Treinos <span class="ml-1 rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px]" x-text="form.workouts.length"></span></button></div>
            <div x-show="tab==='data'" class="max-h-[68vh] overflow-y-auto px-5 py-6 sm:px-7">@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><strong>Revise os dados informados.</strong></div>@endif<div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Nome completo</label><input class="field" name="name" x-model="form.name" required x-ref="nameInput"></div><div><label class="label">E-mail</label><input class="field" type="email" name="email" x-model="form.email" required></div><div><label class="label">Telefone</label><input class="field" name="phone" x-model="form.phone"></div><div><label class="label">Data de nascimento</label><input class="field" type="date" name="birth_date" x-model="form.birth_date"></div><div><label class="label">Senha <span class="font-normal text-slate-400" x-show="mode === 'edit'">(opcional)</span></label><input class="field" type="password" name="password" :required="mode === 'create'"></div><div class="sm:col-span-2"><label class="label">Endereço</label><input class="field" name="address" x-model="form.address"></div><div><label class="label">Status</label><select class="field" name="active" x-model="form.active"><option value="1">Ativo</option><option value="0">Inativo</option></select></div></div></div>
            <div x-show="tab==='workouts'" class="max-h-[68vh] overflow-y-auto px-5 py-6 sm:px-7"><div class="mb-4 flex items-center justify-between gap-3"><div><h3 class="font-bold text-ink-950">Treinos do aluno</h3><p class="text-xs text-slate-500">Atribua, abra ou clone uma ficha.</p></div><a :href="form.assign_url" class="btn-primary"><x-icon name="plus" size="size-4"/>Atribuir novo</a></div><div class="space-y-3"><template x-for="workout in form.workouts" :key="workout.id"><article class="rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-ink-950" x-text="workout.name"></p><p class="text-xs text-slate-500" x-text="`${workout.count} exercícios · ${workout.date}`"></p></div><a :href="workout.open_url" class="text-sm font-bold text-brand-700">Abrir</a></div><a :href="workout.clone_url" class="mt-3 inline-block text-xs font-bold text-slate-500">Clonar para este aluno →</a></article></template><div x-show="form.workouts.length===0" class="rounded-xl bg-slate-50 px-5 py-10 text-center text-sm text-slate-500">Nenhum treino atribuído.</div></div></div>
            <div x-show="tab==='data'" class="flex flex-col-reverse gap-3 border-t border-slate-100 px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button type="button" class="btn-secondary" @click="close()">Cancelar</button><button class="btn-primary" x-text="mode === 'edit' ? 'Salvar alterações' : 'Salvar aluno'"></button></div>
        </form></div></div>
    </div>
    <script>function memberManager(config){const empty=()=>({id:'',name:'',email:'',phone:'',birth_date:'',address:'',active:'1',action:config.storeUrl,workouts:[],assign_url:''});return{modal:false,mode:'create',tab:'data',form:empty(),init(){if(config.initialMode==='edit'&&config.initialMember)this.openEdit(config.initialMember);else if(config.initialMode==='create'){this.mode='create';this.form={...empty(),...(config.initialMember||{})};this.show()}},openCreate(){this.mode='create';this.tab='data';this.form=empty();this.show()},openEdit(item){this.mode='edit';this.tab='data';this.form={...empty(),...item,active:String(item.active)};this.show()},show(){this.modal=true;document.body.classList.add('overflow-hidden');this.$nextTick(()=>this.$refs.nameInput?.focus())},close(){this.modal=false;document.body.classList.remove('overflow-hidden')}}}</script>
</x-layouts.app>
