<x-layouts.app title="Cobranças">
    @php($statusLabels = ['pending' => 'Pendente', 'partial' => 'Parcial', 'paid' => 'Pago', 'overdue' => 'Vencida', 'cancelled' => 'Cancelada'])
    @php($statusClasses = ['pending' => 'bg-amber-50 text-amber-700', 'partial' => 'bg-blue-50 text-blue-700', 'paid' => 'bg-emerald-50 text-emerald-700', 'overdue' => 'bg-red-50 text-red-700', 'cancelled' => 'bg-slate-100 text-slate-500'])
    <div class="grid gap-4 md:grid-cols-3"><div class="card p-6"><p class="text-sm text-slate-500">A receber</p><p class="mt-2 text-3xl font-black text-ink-950">R$ {{ number_format($openAmount, 2, ',', '.') }}</p></div><div class="card border-red-100 p-6"><p class="text-sm text-red-600">Em atraso</p><p class="mt-2 text-3xl font-black text-red-700">R$ {{ number_format($overdueAmount, 2, ',', '.') }}</p></div><div class="card border-emerald-100 p-6"><p class="text-sm text-emerald-600">Recebido neste mês</p><p class="mt-2 text-3xl font-black text-emerald-700">R$ {{ number_format($receivedThisMonth, 2, ',', '.') }}</p></div></div>
    <div class="my-6 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><form class="flex flex-1 flex-col gap-2 sm:flex-row"><input class="field max-w-md" name="search" value="{{ request('search') }}" placeholder="Buscar aluno"><select class="field max-w-48" name="status"><option value="">Todos os status</option>@foreach($statusLabels as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select><button class="btn-secondary">Filtrar</button></form><a href="{{ route('memberships.create') }}" class="btn-primary">+ Nova matrícula</a></div>
    <div class="card overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">Aluno</th><th class="px-5 py-4">Cobrança</th><th class="px-5 py-4">Vencimento</th><th class="px-5 py-4">Total</th><th class="px-5 py-4">Saldo</th><th class="px-5 py-4">Status</th><th class="px-5 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($charges as $charge)<tr class="{{ $charge->status === 'overdue' ? 'bg-red-50/30' : '' }}"><td class="px-5 py-4"><p class="font-bold text-ink-950">{{ $charge->membership->member->name }}</p><p class="text-xs text-slate-500">{{ $charge->membership->plan->name }}</p></td><td class="px-5 py-4">{{ $charge->description }}</td><td class="px-5 py-4 {{ $charge->status === 'overdue' ? 'font-bold text-red-700' : '' }}">{{ $charge->due_date->format('d/m/Y') }}</td><td class="px-5 py-4 font-semibold">R$ {{ number_format($charge->total, 2, ',', '.') }}</td><td class="px-5 py-4 font-semibold">R$ {{ number_format($charge->outstanding, 2, ',', '.') }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $statusClasses[$charge->status] ?? 'bg-slate-100' }}">{{ $statusLabels[$charge->status] ?? $charge->status }}</span></td><td class="px-5 py-4 text-right"><a class="icon-btn" href="{{ route('memberships.show', $charge->membership) }}" title="Abrir cobrança" aria-label="Abrir cobrança de {{ $charge->membership->member->name }}"><x-icon name="eye" size="size-4"/></a></td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">Nenhuma cobrança encontrada.</td></tr>@endforelse
    </tbody></table></div><div class="mt-6">{{ $charges->links() }}</div>
</x-layouts.app>
