<x-layouts.app title="Perfil">
    <div class="grid gap-6 xl:grid-cols-[1fr_380px]">
        <form method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data" class="card p-6 lg:p-8" x-data="{ preview: @js($user->avatar_url), removed: false }">@csrf @method('PUT')
            <div class="mb-8 flex flex-col gap-5 border-b border-slate-100 pb-7 sm:flex-row sm:items-center">
                <div class="relative size-24 shrink-0 overflow-hidden rounded-full bg-brand-100 text-brand-700"><img x-show="preview && !removed" :src="preview" class="size-full object-cover"><div x-show="!preview || removed" class="grid size-full place-items-center text-2xl font-black">{{ $user->initials }}</div></div>
                <div><label class="btn-secondary cursor-pointer">Escolher foto<input type="file" name="avatar" accept="image/png,image/jpeg,image/webp" class="hidden" @change="preview = URL.createObjectURL($event.target.files[0]); removed = false"></label>@if($user->avatar_path)<label class="ml-3 cursor-pointer text-sm font-semibold text-red-600"><input type="checkbox" name="remove_avatar" value="1" class="hidden" x-model="removed"> <span x-text="removed ? 'Manter foto' : 'Remover foto'"></span></label>@endif<p class="mt-2 text-xs text-slate-400">JPG, PNG ou WebP, até 2 MB.</p></div>
            </div>
            <div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Nome completo</label><input class="field" name="name" value="{{ old('name', $user->name) }}" maxlength="120" required></div><div><label class="label">E-mail</label><input class="field" type="email" name="email" value="{{ old('email', $user->email) }}" maxlength="190" required></div><div><label class="label">Telefone</label><input class="field" type="tel" inputmode="tel" name="phone" value="{{ old('phone', $user->phone) }}" maxlength="30" pattern="\+?[0-9() .-]{8,30}" title="Use apenas números e os símbolos + ( ) . -" @input="$event.target.value = $event.target.value.replace(/[^0-9+(). -]/g, '')">@error('phone')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div><div><label class="label">Data de nascimento</label><input class="field" type="date" name="birth_date" value="{{ old('birth_date', $user->birth_date?->format('Y-m-d')) }}" max="{{ today()->subDay()->toDateString() }}"></div><div class="sm:col-span-2"><label class="label">Endereço</label><input class="field" name="address" value="{{ old('address', $user->address) }}" maxlength="255"></div></div>
            <div class="mt-8 flex justify-end"><button class="btn-primary">Salvar perfil</button></div>
        </form>
        <form method="POST" action="{{ route('profile.password') }}" class="card h-fit p-6">@csrf @method('PUT')<h2 class="text-lg font-black text-ink-950">Alterar senha</h2><p class="mt-1 text-sm text-slate-500">Use 12 ou mais caracteres, com maiúscula, minúscula, número e símbolo.</p><div class="mt-6 space-y-4"><div><label class="label">Senha atual</label><input class="field" type="password" name="current_password" required autocomplete="current-password"></div><div><label class="label">Nova senha</label><input class="field" type="password" name="password" required autocomplete="new-password"></div><div><label class="label">Confirmar nova senha</label><input class="field" type="password" name="password_confirmation" required autocomplete="new-password"></div></div><button class="btn-primary mt-6 w-full">Atualizar senha</button></form>
    </div>
</x-layouts.app>
