<x-layouts.app title="Loja">
    <div x-data="shopManager(@js(route('shop.products.store')), @js([
        'hasErrors' => $errors->any() && auth()->user()->isStaff(),
        'mode' => old('product_mode', 'create'),
        'form' => [
            'id' => '',
            'name' => old('name', ''),
            'description' => old('description', ''),
            'price' => old('price', ''),
            'stock' => old('stock', 0),
            'active' => old('active', '1'),
            'action' => old('product_action', route('shop.products.store')),
        ],
    ]))" @keydown.escape.window="closeAll()">
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-black text-ink-950">{{ auth()->user()->isStaff() ? 'Produtos da academia' : 'Produtos para você' }}</h2><p class="mt-1 text-sm text-slate-500">{{ $products->count() }} produto(s) disponível(is)</p></div>@if(auth()->user()->isStaff())<button class="btn-primary" @click="newProduct()"><x-icon name="plus"/>Novo produto</button>@endif</div>
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@forelse($products as $product)@php($productData=['id'=>$product->id,'name'=>$product->name,'description'=>$product->description ?? '','price'=>$product->price,'stock'=>$product->stock,'active'=>$product->active?'1':'0','image_url'=>$product->image_url,'action'=>route('shop.products.update',$product)])<article class="card overflow-hidden">@if($product->image_url)<button type="button" class="block w-full" @click="viewProduct({{ Js::from($productData) }})" aria-label="Ver {{ $product->name }}"><img src="{{ $product->image_url }}" class="h-48 w-full object-cover transition hover:scale-[1.02]" alt="{{ $product->name }}"></button>@else<button type="button" class="grid h-36 w-full place-items-center bg-brand-50 text-brand-700 transition hover:bg-brand-100" @click="viewProduct({{ Js::from($productData) }})" aria-label="Ver {{ $product->name }}"><x-icon name="shop" size="size-10"/></button>@endif<div class="p-5"><div class="flex items-start justify-between gap-3"><div><h3 class="text-lg font-black text-ink-950">{{ $product->name }}</h3><p class="mt-1 text-sm text-slate-500">{{ $product->description ?: 'Produto oferecido pela academia.' }}</p></div>@if(auth()->user()->isStaff())<span class="size-2 rounded-full {{ $product->active?'bg-emerald-500':'bg-slate-300' }}"></span>@endif</div><div class="mt-5 flex items-end justify-between"><div><p class="text-2xl font-black text-ink-950">R$ {{ number_format($product->price,2,',','.') }}</p><p class="text-xs text-slate-400">{{ $product->stock }} em estoque</p></div><div class="flex items-center gap-2"><button class="icon-btn" title="Ver produto" aria-label="Ver {{ $product->name }}" @click="viewProduct({{ Js::from($productData) }})"><x-icon name="eye" size="size-4"/></button>@if(auth()->user()->isStaff())<button class="icon-btn" title="Editar produto" aria-label="Editar {{ $product->name }}" @click="editProduct({{ Js::from($productData) }})"><x-icon name="edit" size="size-4"/></button>@else<form method="POST" action="{{ route('shop.order',$product) }}" class="flex items-center gap-2">@csrf<input type="number" name="quantity" value="1" min="1" max="{{ min(20,$product->stock) }}" class="field w-16 px-2"><button class="btn-primary">Pedir</button></form>@endif</div></div></div></article>@empty<div class="card col-span-full px-6 py-14 text-center text-slate-500">Nenhum produto disponível.</div>@endforelse</div>
        @if($orders->isNotEmpty())<section class="mt-9"><h2 class="mb-4 text-lg font-black text-ink-950">{{ auth()->user()->isStaff() ? 'Pedidos recentes' : 'Meus pedidos' }}</h2><div class="space-y-3">@foreach($orders as $order)<div class="card flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div class="flex-1"><p class="font-bold text-ink-950">Pedido #{{ $order->id }} @if(auth()->user()->isStaff())· {{ $order->member->name }}@endif</p><p class="text-xs text-slate-500">{{ $order->items->pluck('product_name')->join(', ') }} · {{ $order->ordered_at->format('d/m/Y H:i') }}</p></div><div class="flex items-center justify-between gap-4"><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">{{ $order->status === 'pending' ? 'Aguardando confirmação' : ucfirst($order->status) }}</span><strong>R$ {{ number_format($order->total,2,',','.') }}</strong></div></div>@endforeach</div></section>@endif

        <div x-show="viewer" x-cloak class="fixed inset-0 z-50 overflow-y-auto" role="dialog" aria-modal="true" aria-label="Detalhes do produto"><div class="flex min-h-full items-end justify-center sm:items-center sm:p-6"><div class="fixed inset-0 bg-ink-950/65 backdrop-blur-sm" @click="closeViewer()"></div><article class="relative w-full overflow-hidden rounded-t-3xl bg-white shadow-2xl sm:max-w-3xl sm:rounded-3xl"><button type="button" class="absolute right-4 top-4 z-10 grid size-10 place-items-center rounded-full bg-white/90 text-slate-600 shadow hover:bg-white" @click="closeViewer()" aria-label="Fechar"><x-icon name="close"/></button><div class="grid sm:grid-cols-2"><div class="min-h-72 bg-slate-100"><template x-if="viewerProduct.image_url"><img :src="viewerProduct.image_url" :alt="viewerProduct.name" class="h-full min-h-72 w-full object-contain"></template><template x-if="!viewerProduct.image_url"><div class="grid h-full min-h-72 place-items-center bg-brand-50 text-brand-700"><x-icon name="shop" size="size-16"/></div></template></div><div class="flex flex-col p-6 sm:p-8"><div class="flex-1"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold" :class="viewerProduct.active==='1'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'" x-text="viewerProduct.active==='1'?'Produto ativo':'Produto inativo'"></span><h2 class="mt-4 text-3xl font-black text-ink-950" x-text="viewerProduct.name"></h2><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-500" x-text="viewerProduct.description || 'Produto oferecido pela academia.'"></p><p class="mt-7 text-3xl font-black text-ink-950" x-text="formatPrice(viewerProduct.price)"></p><p class="mt-1 text-sm text-slate-500"><strong x-text="viewerProduct.stock"></strong> unidade(s) em estoque</p></div>@if(auth()->user()->isStaff())<button type="button" class="btn-primary mt-8 w-full" @click="editViewedProduct()"><x-icon name="edit" size="size-4"/>Editar produto</button>@endif</div></div></article></div></div>

        @if(auth()->user()->isStaff())<div x-show="modal" x-cloak class="fixed inset-0 z-50"><div class="fixed inset-0 bg-ink-950/65 backdrop-blur-sm" @click="close()"></div><form :action="form.action" method="POST" enctype="multipart/form-data" class="relative mx-auto flex h-[100dvh] max-w-2xl flex-col bg-white sm:my-8 sm:h-auto sm:max-h-[90vh] sm:rounded-3xl">@csrf<input type="hidden" name="product_mode" :value="mode"><input type="hidden" name="product_action" :value="form.action"><template x-if="mode==='edit'"><input type="hidden" name="_method" value="PUT"></template><div class="flex items-center justify-between border-b p-5"><h2 class="text-xl font-black" x-text="mode==='edit'?'Editar produto':'Novo produto'"></h2><button type="button" @click="close()"><x-icon name="close"/></button></div><div class="grid flex-1 gap-5 overflow-y-auto p-5 sm:grid-cols-2">@if($errors->any())<div class="sm:col-span-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"><strong>Revise os dados:</strong><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<div class="sm:col-span-2"><label class="label">Nome</label><input class="field" name="name" x-model="form.name" required></div><div><label class="label">Preço</label><input class="field" type="number" step="0.01" min="0.01" name="price" x-model="form.price" required></div><div><label class="label">Estoque</label><input class="field" type="number" min="0" name="stock" x-model="form.stock" required></div><div><label class="label">Status</label><select class="field" name="active" x-model="form.active"><option value="1">Ativo</option><option value="0">Inativo</option></select></div><div><label class="label">Imagem</label><input class="field" type="file" name="image" accept="image/png,image/jpeg,image/gif,image/bmp,image/webp"><p class="mt-1 text-xs text-slate-400">JPG, PNG, GIF, BMP ou WebP, até 3 MB.</p></div><div class="sm:col-span-2"><label class="label">Descrição</label><textarea class="field" name="description" rows="3" x-model="form.description"></textarea></div></div><div class="border-t p-4"><button class="btn-primary w-full" x-text="mode==='edit'?'Salvar produto':'Cadastrar produto'"></button></div></form></div>@endif
    </div>
    <script>function shopManager(storeUrl,initial){const empty=()=>({id:'',name:'',description:'',price:'',stock:0,active:'1',image_url:null,action:storeUrl});const hasErrors=Boolean(initial?.hasErrors);return{modal:hasErrors,viewer:false,viewerProduct:empty(),mode:hasErrors?initial.mode:'create',form:hasErrors?initial.form:empty(),init(){if(this.modal)document.body.classList.add('overflow-hidden')},formatPrice(value){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0)},newProduct(){this.mode='create';this.form=empty();this.open()},viewProduct(p){this.viewerProduct={...p,active:String(p.active)};this.viewer=true;document.body.classList.add('overflow-hidden')},editViewedProduct(){const product={...this.viewerProduct};this.closeViewer();this.editProduct(product)},editProduct(p){this.mode='edit';this.form={...p,active:String(p.active)};this.open()},open(){this.modal=true;document.body.classList.add('overflow-hidden')},close(){this.modal=false;document.body.classList.remove('overflow-hidden')},closeViewer(){this.viewer=false;document.body.classList.remove('overflow-hidden')},closeAll(){if(this.modal)this.close();if(this.viewer)this.closeViewer()}}}</script>
</x-layouts.app>
