<x-layouts.app title="Planos">
    @php
        $oldModal = old('plan_modal');
        $initialPlan = $modalPlan ? ['id' => $modalPlan->id, 'name' => $modalPlan->name, 'price' => $modalPlan->price, 'enrollment_fee' => $modalPlan->enrollment_fee, 'billing_interval_months' => (string) $modalPlan->billing_interval_months, 'description' => $modalPlan->description ?? '', 'active' => $modalPlan->active ? '1' : '0', 'action' => route('plans.update', $modalPlan)] : null;
        $oldPlan = $oldModal ? ['id' => old('plan_id'), 'name' => old('name'), 'price' => old('price'), 'enrollment_fee' => old('enrollment_fee', 0), 'billing_interval_months' => old('billing_interval_months', '1'), 'description' => old('description', ''), 'active' => old('active', '1'), 'action' => old('plan_action')] : null;
    @endphp
    <div x-data="planManager({storeUrl:@js(route('plans.store')),initialMode:@js($oldModal ?: request('modal')),initialPlan:@js($oldPlan ?: $initialPlan)})" @keydown.escape.window="close()">
        <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-black text-ink-950">Planos disponíveis</h2><p class="mt-1 text-sm text-slate-500">{{ $plans->count() }} {{ $plans->count() === 1 ? 'plano cadastrado' : 'planos cadastrados' }}</p></div><button type="button" class="btn-primary w-full sm:w-auto" @click="openCreate()"><x-icon name="plus" />Novo plano</button></div>
        <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($plans as $plan)<article class="card p-6"><div class="flex items-start justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-brand-600">A cada {{ $plan->billing_interval_months }} {{ $plan->billing_interval_months === 1 ? 'mês' : 'meses' }}</p><h2 class="mt-2 text-xl font-black text-ink-950">{{ $plan->name }}</h2></div><span class="size-2 rounded-full {{ $plan->active ? 'bg-emerald-500' : 'bg-slate-300' }}"></span></div><p class="mt-5 text-3xl font-black text-ink-950"><span class="text-sm font-semibold text-slate-400">R$</span> {{ number_format($plan->price, 2, ',', '.') }}</p><p class="mt-2 text-sm text-slate-500">Matrícula: R$ {{ number_format($plan->enrollment_fee, 2, ',', '.') }}</p><p class="mt-4 min-h-10 text-sm text-slate-500">{{ $plan->description ?: 'Sem descrição adicional.' }}</p><div class="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span class="text-xs font-semibold text-slate-500">{{ $plan->memberships_count }} matrícula(s) ativa(s)</span><button type="button" class="icon-btn" title="Editar plano" aria-label="Editar {{ $plan->name }}" @click="openEdit({{ Js::from(['id'=>$plan->id,'name'=>$plan->name,'price'=>$plan->price,'enrollment_fee'=>$plan->enrollment_fee,'billing_interval_months'=>(string)$plan->billing_interval_months,'description'=>$plan->description ?? '','active'=>$plan->active?'1':'0','action'=>route('plans.update',$plan)]) }})"><x-icon name="edit" size="size-4"/></button></div></article>@empty<p class="col-span-full py-12 text-center text-slate-500">Nenhum plano cadastrado.</p>@endforelse</div>

        <div x-show="modal" x-cloak class="fixed inset-0 z-50 overflow-y-auto" role="dialog" aria-modal="true"><div class="flex min-h-full items-end justify-center sm:items-center sm:p-6"><div class="fixed inset-0 bg-ink-950/65 backdrop-blur-sm" @click="close()"></div><form :action="form.action" method="POST" class="relative w-full rounded-t-3xl bg-white shadow-2xl sm:max-w-2xl sm:rounded-3xl">@csrf<template x-if="mode==='edit'"><input type="hidden" name="_method" value="PUT"></template><input type="hidden" name="plan_modal" :value="mode"><input type="hidden" name="plan_id" :value="form.id"><input type="hidden" name="plan_action" :value="form.action"><div class="flex items-start justify-between border-b border-slate-100 px-5 py-5 sm:px-7"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-brand-600" x-text="mode==='edit'?'Atualizar plano':'Novo cadastro'"></p><h2 class="mt-1 text-xl font-black text-ink-950" x-text="mode==='edit'?'Editar plano':'Novo plano'"></h2></div><button type="button" class="grid size-10 place-items-center rounded-xl text-slate-400 hover:bg-slate-100" @click="close()"><x-icon name="close"/></button></div><div class="max-h-[68vh] overflow-y-auto px-5 py-6 sm:px-7">@if($errors->any())<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">Revise os dados informados.</div>@endif<div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label">Nome do plano</label><input class="field" name="name" x-model="form.name" required x-ref="nameInput"></div><div><label class="label">Valor recorrente</label><input class="field" type="number" min="0.01" step="0.01" name="price" x-model="form.price" required></div><div><label class="label">Taxa de matrícula</label><input class="field" type="number" min="0" step="0.01" name="enrollment_fee" x-model="form.enrollment_fee" required></div><div><label class="label">Periodicidade</label><select class="field" name="billing_interval_months" x-model="form.billing_interval_months"><option value="1">Mensal</option><option value="3">Trimestral</option><option value="6">Semestral</option><option value="12">Anual</option></select></div><div><label class="label">Status</label><select class="field" name="active" x-model="form.active"><option value="1">Ativo</option><option value="0">Inativo</option></select></div><div class="sm:col-span-2"><label class="label">Descrição</label><textarea class="field" name="description" rows="3" x-model="form.description"></textarea></div></div><div x-show="mode==='edit'" class="mt-5 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-800">Alterar o valor afeta apenas novas matrículas.</div></div><div class="flex flex-col-reverse gap-3 border-t border-slate-100 px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><button type="button" class="btn-secondary" @click="close()">Cancelar</button><button class="btn-primary" x-text="mode==='edit'?'Salvar alterações':'Salvar plano'"></button></div></form></div></div>
    </div>
    <script>function planManager(c){const empty=()=>({id:'',name:'',price:'',enrollment_fee:'0',billing_interval_months:'1',description:'',active:'1',action:c.storeUrl});return{modal:false,mode:'create',form:empty(),init(){if(c.initialMode==='edit'&&c.initialPlan)this.openEdit(c.initialPlan);else if(c.initialMode==='create'){this.mode='create';this.form={...empty(),...(c.initialPlan||{})};this.show()}},openCreate(){this.mode='create';this.form=empty();this.show()},openEdit(x){this.mode='edit';this.form={...empty(),...x,billing_interval_months:String(x.billing_interval_months),active:String(x.active)};this.show()},show(){this.modal=true;document.body.classList.add('overflow-hidden');this.$nextTick(()=>this.$refs.nameInput?.focus())},close(){this.modal=false;document.body.classList.remove('overflow-hidden')}}}</script>
</x-layouts.app>
