<x-layouts.app title="Atribuir treino">
    @php
        $itemData=fn($items)=>$items->map(fn($item)=>['exercise_id'=>(string)$item->exercise_id,'sets'=>$item->sets,'repetitions'=>$item->repetitions,'weight'=>'','rest_seconds'=>$item->rest_seconds,'notes'=>''])->values()->all();
        $sourceData=$templates->map(fn($template)=>['key'=>'template-'.$template->id,'type'=>'template','id'=>$template->id,'name'=>$template->name,'subtitle'=>$template->items->count().' exercícios · modelo','items'=>$itemData($template->items)])
            ->concat($reusableWorkouts->map(fn($workout)=>['key'=>'workout-'.$workout->id,'type'=>'workout','id'=>$workout->id,'name'=>$workout->name,'subtitle'=>$workout->items->count().' exercícios · '.$workout->member->name,'items'=>$itemData($workout->items)]))->values();
    @endphp
    <form method="POST" action="{{ route('workouts.store') }}" x-data="workoutBuilder({sources:@js($sourceData),initialSource:@js(request('template_id') ? 'template-'.request('template_id') : (request('source_workout_id') ? 'workout-'.request('source_workout_id') : '')),initialMember:@js((string)old('member_id',request('member_id','')))})" @keydown.escape.window="sourceModal=false">@csrf
        <input type="hidden" name="workout_template_id" :value="templateId"><input type="hidden" name="source_workout_id" :value="sourceWorkoutId">
        <div class="card p-6 lg:p-8"><h2 class="text-lg font-black text-ink-950">Informações do treino</h2><div class="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-4">
            <div class="xl:col-span-2"><label class="label">Origem da ficha</label><button type="button" class="field flex items-center justify-between text-left" @click="sourceModal=true"><span><strong class="block text-sm" x-text="selectedSourceName"></strong><small class="text-xs text-slate-400" x-text="selectedSource ? 'Clique para trocar a estrutura' : 'Clique para usar um treino ou modelo existente'"></small></span><span class="text-brand-700">Escolher</span></button></div>
            <div class="xl:col-span-2"><label class="label">Atribuir ao aluno</label><select class="field" name="member_id" x-model="memberId" required><option value="">Selecione quem receberá este treino</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-400">A ficha ficará disponível imediatamente no acesso do aluno.</p></div>
            <div class="xl:col-span-2"><label class="label">Nome do treino</label><input class="field" name="name" x-model="trainingName" placeholder="Ex.: A — Peitoral e tríceps" required></div>
            <div><label class="label">Início</label><input class="field" type="date" name="starts_at" value="{{ old('starts_at', now()->format('Y-m-d')) }}" required></div><div><label class="label">Término</label><input class="field" type="date" name="ends_at" value="{{ old('ends_at') }}"></div>
            <div class="md:col-span-2"><label class="label">Observações gerais</label><input class="field" name="notes" value="{{ old('notes') }}"></div>
        </div></div>
        <div class="card mt-6 p-6 lg:p-8">
            <div class="flex items-center justify-between"><div><h2 class="text-lg font-black text-ink-950">Exercícios</h2><p class="text-sm text-slate-500">A ordem abaixo será a ordem da ficha.</p></div><button type="button" class="icon-btn" title="Adicionar exercício" aria-label="Adicionar exercício" @click="items.push({ exercise_id: '', sets: 3, repetitions: '8-12', weight: '', rest_seconds: 60, notes: '' })"><x-icon name="plus"/></button></div>
            <div class="mt-6 space-y-4"><template x-for="(item, index) in items" :key="index"><div class="rounded-2xl border border-slate-200 bg-slate-50 p-4">
                <div class="mb-4 flex items-center justify-between"><span class="grid size-8 place-items-center rounded-full bg-ink-950 text-xs font-bold text-white" x-text="index + 1"></span><button type="button" class="icon-btn-danger disabled:opacity-30" title="Remover exercício" aria-label="Remover exercício" :disabled="items.length === 1" @click="items.splice(index, 1)"><x-icon name="trash" size="size-4"/></button></div>
                <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
                    <div class="xl:col-span-2"><label class="label">Exercício</label><select class="field" :name="`items[${index}][exercise_id]`" x-model="item.exercise_id" required><option value="">Selecione</option>@foreach($exercises->groupBy(fn ($exercise) => $exercise->muscleGroup?->name ?? 'Outros') as $groupName => $groupExercises)<optgroup label="{{ $groupName }}">@foreach($groupExercises as $exercise)<option value="{{ $exercise->id }}">{{ $exercise->name }}</option>@endforeach</optgroup>@endforeach</select></div>
                    <div><label class="label">Séries</label><input class="field" type="number" min="1" max="20" :name="`items[${index}][sets]`" x-model="item.sets" required></div><div><label class="label">Repetições</label><input class="field" :name="`items[${index}][repetitions]`" x-model="item.repetitions" required></div><div><label class="label">Carga (kg)</label><input class="field" type="number" min="0" step="0.01" :name="`items[${index}][weight]`" x-model="item.weight"></div><div><label class="label">Descanso (s)</label><input class="field" type="number" min="0" :name="`items[${index}][rest_seconds]`" x-model="item.rest_seconds"></div>
                    <div class="md:col-span-2 xl:col-span-6"><label class="label">Observação</label><input class="field" :name="`items[${index}][notes]`" x-model="item.notes" placeholder="Cadência, técnica, ajuste..."></div>
                </div>
            </div></template></div>
        </div><div class="mt-6 flex flex-col-reverse justify-end gap-3 sm:flex-row"><a class="btn-secondary" href="{{ route('workouts.index') }}">Cancelar</a><button class="btn-primary">Salvar treino</button></div>
        <div x-show="sourceModal" x-cloak class="fixed inset-0 z-50"><div class="fixed inset-0 bg-ink-950/65 backdrop-blur-sm" @click="sourceModal=false"></div><div class="relative flex h-[100dvh] w-full flex-col bg-white sm:absolute sm:left-1/2 sm:top-1/2 sm:h-auto sm:max-h-[85vh] sm:max-w-2xl sm:-translate-x-1/2 sm:-translate-y-1/2 sm:rounded-3xl"><div class="flex items-center justify-between border-b p-5"><div><p class="text-xs font-bold uppercase tracking-wider text-brand-600">Reaproveitar</p><h2 class="text-xl font-black text-ink-950">Escolher estrutura</h2></div><button type="button" @click="sourceModal=false"><x-icon name="close"/></button></div><div class="border-b p-4 sm:px-6"><div class="relative"><x-icon name="search" size="size-4" class="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input class="field pl-10" x-model="sourceSearch" placeholder="Buscar treino, modelo ou aluno"></div></div><div class="flex-1 space-y-2 overflow-y-auto p-4 sm:p-6"><button type="button" class="flex w-full items-center justify-between rounded-xl border p-4 text-left" :class="selectedSource===''?'border-brand-500 bg-brand-50':'border-slate-200'" @click="blankWorkout();sourceModal=false"><div><p class="font-bold text-ink-950">Ficha em branco</p><p class="text-xs text-slate-500">Montar exercício por exercício</p></div><span x-show="selectedSource===''" class="text-brand-700">✓</span></button><template x-for="source in filteredSources" :key="source.key"><button type="button" class="flex w-full items-center justify-between gap-3 rounded-xl border p-4 text-left" :class="selectedSource===source.key?'border-brand-500 bg-brand-50':'border-slate-200 hover:border-slate-300'" @click="applySource(source);sourceModal=false"><div class="min-w-0"><p class="truncate font-bold text-ink-950" x-text="source.name"></p><p class="truncate text-xs text-slate-500" x-text="source.subtitle"></p></div><span x-show="selectedSource===source.key" class="text-brand-700">✓</span></button></template><p x-show="filteredSources.length===0" class="py-10 text-center text-sm text-slate-500">Nenhuma estrutura encontrada.</p></div></div></div>
    </form>
    <script>function workoutBuilder(config){return{sources:config.sources,selectedSource:'',templateId:'',sourceWorkoutId:'',sourceModal:false,sourceSearch:'',memberId:config.initialMember,trainingName:@js(old('name','')),items:[{exercise_id:'',sets:3,repetitions:'8-12',weight:'',rest_seconds:60,notes:''}],init(){if(config.initialSource){const source=this.sources.find(item=>item.key===config.initialSource);if(source)this.applySource(source)}},get filteredSources(){const query=this.sourceSearch.toLowerCase().trim();return query?this.sources.filter(item=>(item.name+' '+item.subtitle).toLowerCase().includes(query)):this.sources},get selectedSourceName(){return this.sources.find(item=>item.key===this.selectedSource)?.name||'Ficha em branco'},blankWorkout(){this.selectedSource='';this.templateId='';this.sourceWorkoutId='';this.items=[{exercise_id:'',sets:3,repetitions:'8-12',weight:'',rest_seconds:60,notes:''}]},applySource(source){this.selectedSource=source.key;this.templateId=source.type==='template'?source.id:'';this.sourceWorkoutId=source.type==='workout'?source.id:'';this.items=source.items.map(item=>({...item}));if(!this.trainingName)this.trainingName=source.name}}}</script>
</x-layouts.app>
