<x-layouts.app title="Treinos">
    <div x-data="{ tab: @js(request('view') === 'models' ? 'models' : 'assigned') }">
        @if(auth()->user()->isStaff())
            <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm text-slate-500">Gerencie fichas atribuídas e estruturas reutilizáveis.</p><p class="mt-1 text-sm font-semibold text-ink-950">{{ $workouts->total() }} treino(s) · {{ $templates->count() }} modelo(s)</p></div><a class="btn-primary w-full sm:w-auto" href="{{ route('workouts.create') }}"><x-icon name="plus" />Atribuir treino</a></div>
            <div class="mb-6 inline-flex w-full rounded-xl bg-slate-100 p-1 sm:w-auto"><button type="button" class="flex-1 rounded-lg px-4 py-2 text-sm font-bold transition sm:flex-none" :class="tab==='assigned'?'bg-white text-ink-950 shadow-sm':'text-slate-500'" @click="tab='assigned'">Treinos atribuídos</button><button type="button" class="flex-1 rounded-lg px-4 py-2 text-sm font-bold transition sm:flex-none" :class="tab==='models'?'bg-white text-ink-950 shadow-sm':'text-slate-500'" @click="tab='models'">Modelos</button></div>
        @else
            <div class="mb-6"><p class="text-sm text-slate-500">Acompanhe as fichas atribuídas a você.</p><p class="mt-1 text-sm font-semibold text-ink-950">{{ $workouts->total() }} treino(s)</p></div>
        @endif
        <section x-show="tab==='assigned'">
            @if(auth()->user()->isStaff())<form class="card mb-6 flex gap-3 p-4"><div class="flex-1"><label class="label">Filtrar por aluno</label><select class="field" name="member_id"><option value="">Todos os alunos</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected(request('member_id')==$member->id)>{{ $member->name }}</option>@endforeach</select></div><button class="icon-btn self-end" title="Aplicar filtro" aria-label="Aplicar filtro"><x-icon name="filter" size="size-4"/></button></form>@endif
            <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@forelse($workouts as $workout)<article class="card p-5 sm:p-6"><div class="flex justify-between gap-3"><span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-bold text-brand-700">{{ $workout->items->count() }} exercícios</span><span class="text-xs text-slate-400">{{ $workout->starts_at->format('d/m/Y') }}</span></div><h2 class="mt-5 text-lg font-black text-ink-950 sm:text-xl">{{ $workout->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $workout->member->name }}</p><div class="mt-5 flex justify-end gap-2"><a href="{{ route('workouts.show',$workout) }}" class="icon-btn" title="Abrir ficha" aria-label="Abrir {{ $workout->name }}"><x-icon name="eye" size="size-4"/></a>@if(auth()->user()->isStaff())<a href="{{ route('workouts.create',['source_workout_id'=>$workout->id]) }}" class="icon-btn" title="Clonar treino" aria-label="Clonar {{ $workout->name }}"><x-icon name="clone" size="size-4"/></a>@endif</div></article>@empty<div class="card col-span-full px-6 py-14 text-center text-slate-500">Nenhum treino encontrado.</div>@endforelse</div><div class="mt-6">{{ $workouts->links() }}</div>
        </section>
        @if(auth()->user()->isStaff())<section x-show="tab==='models'" x-cloak><div class="mb-4"><h2 class="font-black text-ink-950">Biblioteca de modelos</h2><p class="text-sm text-slate-500">Estruturas sem cargas individuais.</p></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@forelse($templates as $template)<article class="card p-5"><span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-bold text-violet-700">Modelo · {{ $template->items->count() }} exercícios</span><h3 class="mt-4 text-lg font-black text-ink-950">{{ $template->name }}</h3><p class="mt-1 text-sm text-slate-500">Criado por {{ $template->author->name }}</p><div class="mt-5 flex justify-end gap-2"><a class="icon-btn" href="{{ route('workouts.create',['template_id'=>$template->id]) }}" title="Usar modelo" aria-label="Usar modelo {{ $template->name }}"><x-icon name="clone" size="size-4"/></a><form method="POST" action="{{ route('workout-templates.destroy',$template) }}" onsubmit="return confirm('Arquivar este modelo?')">@csrf @method('DELETE')<button class="icon-btn-danger" title="Arquivar modelo" aria-label="Arquivar {{ $template->name }}"><x-icon name="trash" size="size-4"/></button></form></div></article>@empty<div class="card col-span-full px-6 py-14 text-center"><p class="font-bold text-ink-950">Nenhum modelo criado</p><p class="mt-1 text-sm text-slate-500">Abra uma ficha existente e use “Salvar como modelo”.</p></div>@endforelse</div></section>@endif
    </div>
</x-layouts.app>
