<x-layouts.app title="Minhas mensalidades">
    @php($statusLabels=['pending'=>'Pendente','partial'=>'Pagamento parcial','paid'=>'Pago','overdue'=>'Em atraso','cancelled'=>'Cancelada'])
    <section class="mb-6 rounded-3xl bg-ink-950 p-6 text-white sm:p-8"><p class="text-sm text-brand-500">Resumo financeiro</p><div class="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-3xl font-black">R$ {{ number_format($openAmount,2,',','.') }}</h2><p class="mt-1 text-sm text-slate-400">Total pendente</p></div><p class="max-w-md text-sm text-slate-300">Consulte vencimentos, pagamentos e eventuais débitos vinculados à sua matrícula.</p></div></section>
    @forelse($memberships as $membership)
        <section class="mb-7"><div class="mb-3"><h2 class="font-black text-ink-950">{{ $membership->plan->name }}</h2><p class="text-sm text-slate-500">Matrícula {{ $membership->status === 'active' ? 'ativa' : $membership->status }} · vencimento dia {{ $membership->billing_day }}</p></div><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        @forelse($membership->charges as $charge)<article class="card p-5"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-ink-950">{{ $charge->description }}</p><p class="mt-1 text-xs text-slate-500">Vence em {{ $charge->due_date->format('d/m/Y') }}</p></div><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{ $charge->status==='paid'?'bg-emerald-50 text-emerald-700':($charge->status==='overdue'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700') }}">{{ $statusLabels[$charge->status]??$charge->status }}</span></div><div class="mt-5 flex items-end justify-between"><div><p class="text-xs text-slate-400">Valor</p><p class="text-xl font-black text-ink-950">R$ {{ number_format($charge->total,2,',','.') }}</p></div>@if((float)$charge->outstanding>0)<div class="text-right"><p class="text-xs text-slate-400">Em aberto</p><p class="font-bold text-red-600">R$ {{ number_format($charge->outstanding,2,',','.') }}</p></div>@endif</div>@if($charge->payments->isNotEmpty())<p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-500">Último pagamento: {{ $charge->payments->first()->paid_at->format('d/m/Y') }}</p>@endif</article>@empty<p class="text-sm text-slate-500">Nenhuma mensalidade gerada.</p>@endforelse
        </div></section>
    @empty<div class="card px-6 py-14 text-center"><p class="font-bold text-ink-950">Você ainda não possui matrícula.</p><p class="mt-1 text-sm text-slate-500">Procure a academia para conhecer os planos.</p></div>@endforelse
</x-layouts.app>
